/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalInterfaces;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ophiran
 */
public class GameBoard extends javax.swing.JPanel {

    private JLabel[][] boardPieces; 
    private ImageIcon whitePiece;
    private ImageIcon blackPiece;
    
    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
        initBoard();
        /*
        try {
            tmpPic = ImageIO.read(this.getClass().getResourceAsStream("/ressources/board.jpg"));
            image = new JLabel(new ImageIcon(tmpPic));
        } catch (IOException ex) {
            Logger.getLogger(OthelloMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jPanelBoard.setLayout(new BorderLayout());
        jPanelBoard.add(image);
        jPanelBoard.repaint();*/
    }
    
    public final void initBoard(){
        float xSize = jLabel1.getIcon().getIconWidth()/8;
        float ySize = jLabel1.getIcon().getIconHeight()/8;
        System.out.println("The board steps are : " + xSize + " by " + ySize);
        boardPieces = new JLabel[8][8];
        for(int yCoord = 0; yCoord < 8; yCoord++){
            for(int xCoord = 0; xCoord <8; xCoord++){
                boardPieces[xCoord][yCoord].setLocation((int)(xSize * xCoord + xSize),(int)(ySize * yCoord + ySize) );
                boardPieces[xCoord][yCoord].setVisible(true);
            }
        }
    }
    
    public void placePiece(int boardX, int boardY){
        //62.5*X + 62.5/2
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/board.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
