/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package othelloclient;

import java.awt.Image;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Ophiran
 */
public class OthelloMainWindow extends javax.swing.JFrame {

    private MenuPanel menuPanel;
    private GameBoard gameBoard;
    private ChatPanel chatPanel;
    private JPanel mainPanel;
    
    private Image tmpPic = null;
    private JLabel image;
    /**
     * Creates new form OthelloMainWindow
     */
    public OthelloMainWindow(){
        initComponents();
        /*
        try {
            tmpPic = ImageIO.read(this.getClass().getResourceAsStream("/ressources/board.jpg"));
            image = new JLabel(new ImageIcon(tmpPic));
        } catch (IOException ex) {
            Logger.getLogger(OthelloMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jPanelBoard.setLayout(new BorderLayout());
        jPanelBoard.add(image);
        jPanelBoard.repaint();*/
        
        menuPanel = new MenuPanel();
        menuPanel.setVisible(true);
        gameBoard = new GameBoard();
        gameBoard.setVisible(true);
        chatPanel = new ChatPanel();
        chatPanel.setVisible(true);
        mainPanel = new JPanel();
        mainPanel.setVisible(true);
        
        
        GroupLayout layout = new GroupLayout(this.getContentPane());
        GroupLayout layoutMainPanel = new GroupLayout(mainPanel);
        
        //Layout for MainPanel
        mainPanel.setLayout(layoutMainPanel);
        layoutMainPanel.setAutoCreateGaps(true);
        layoutMainPanel.setAutoCreateContainerGaps(true);
        
        GroupLayout.SequentialGroup hGroupMP = layoutMainPanel.createSequentialGroup();
        hGroupMP.addGroup(layoutMainPanel.createParallelGroup().addComponent(menuPanel));
        hGroupMP.addGroup(layoutMainPanel.createParallelGroup().addComponent(gameBoard));
        layoutMainPanel.setHorizontalGroup(hGroupMP);
        
        GroupLayout.SequentialGroup vGroupMP = layoutMainPanel.createSequentialGroup();
        vGroupMP.addGroup(layoutMainPanel.createParallelGroup(Alignment.BASELINE).addComponent(menuPanel).addComponent(gameBoard));
        layoutMainPanel.setVerticalGroup(vGroupMP);
        
        //Layout for JFrame
        this.getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        //Create horizontal group (JFrame)
        GroupLayout.SequentialGroup hGroup = layout.createSequentialGroup();
        hGroup.addGroup(layout.createParallelGroup().addComponent(mainPanel).addComponent(chatPanel));
        layout.setHorizontalGroup(hGroup);
        
        //Create vertical group (JFrame)
        GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();
        vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(mainPanel));
        vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(chatPanel));
        layout.setVerticalGroup(vGroup);
        
        
        //this.getContentPane().add(menuPanel);
        pack();
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
